
pub enum Router {
    Linear(FuturesRoute),
    Inverse(FuturesRoute),
}

#[derive(Debug,Clone)]
pub enum FuturesRoute {
    Ping,
    Time,
    ExchangeInfo,
    Depth,
    Trades,
    HistoricalTrades,
    AggTrades,
    Klines,
    ContinuousKlines,
    IndexPriceKlines,
    MarkPriceKlines,
    PremiumIndex,
    FundingRate,
    Ticker24hr,
    TickerPrice,
    BookTicker,
    AllForceOrders,
    AllOpenOrders,
    AllOrders,
    UserTrades,
    Order,
    PositionRisk,
    LeverageBracket,
    Balance,
    PositionSide,
    OpenInterest,
    OpenInterestHist,
    TopLongShortAccountRatio,
    TopLongShortPositionRatio,
    GlobalLongShortAccountRatio,
    TakerlongshortRatio,
    LvtKlines,
    IndexInfo,
    ChangeInitialLeverage,
    Account,
    OpenOrders,
    UserDataStream,
    Income,
}

impl From<Router> for String {
    fn from(item: Router) -> Self {
        String::from(match item {
            Router::Linear(route) => match route {
                FuturesRoute::Ping => "/fapi/v1/ping",
                FuturesRoute::Time => "/fapi/v1/time",
                FuturesRoute::ExchangeInfo => "/fapi/v1/exchangeInfo",
                FuturesRoute::Depth => "/fapi/v1/depth",
                FuturesRoute::Trades => "/fapi/v1/trades",
                FuturesRoute::HistoricalTrades => "/fapi/v1/historicalTrades",
                FuturesRoute::AggTrades => "/fapi/v1/aggTrades",
                FuturesRoute::Klines => "/fapi/v1/klines",
                FuturesRoute::ContinuousKlines => "/fapi/v1/continuousKlines",
                FuturesRoute::IndexPriceKlines => "/fapi/v1/indexPriceKlines",
                FuturesRoute::MarkPriceKlines => "/fapi/v1/markPriceKlines",
                FuturesRoute::PremiumIndex => "/fapi/v1/premiumIndex",
                FuturesRoute::FundingRate => "/fapi/v1/fundingRate",
                FuturesRoute::Ticker24hr => "/fapi/v1/ticker/24hr",
                FuturesRoute::TickerPrice => "/fapi/v1/ticker/price",
                FuturesRoute::BookTicker => "/fapi/v1/ticker/bookTicker",
                FuturesRoute::AllForceOrders => "/fapi/v1/allForceOrders",
                FuturesRoute::AllOpenOrders => "/fapi/v1/allOpenOrders",
                FuturesRoute::AllOrders => "/fapi/v1/allOrders",
                FuturesRoute::UserTrades => "/fapi/v1/userTrades",
                FuturesRoute::PositionSide => "/fapi/v1/positionSide/dual",
                FuturesRoute::Order => "/fapi/v1/order",
                FuturesRoute::PositionRisk => "/fapi/v2/positionRisk",
                FuturesRoute::LeverageBracket => "/fapi/v1/leverageBracket",
                FuturesRoute::Balance => "/fapi/v2/balance",
                FuturesRoute::OpenInterest => "/fapi/v1/openInterest",
                FuturesRoute::OpenInterestHist => "/futures/data/openInterestHist",
                FuturesRoute::TopLongShortAccountRatio => "/futures/data/topLongShortAccountRatio",
                FuturesRoute::TopLongShortPositionRatio => "/futures/data/topLongShortPositionRatio",
                FuturesRoute::GlobalLongShortAccountRatio => "/futures/data/globalLongShortAccountRatio",
                FuturesRoute::TakerlongshortRatio => "/futures/data/takerlongshortRatio",
                FuturesRoute::LvtKlines => "/fapi/v1/lvtKlines",
                FuturesRoute::IndexInfo => "/fapi/v1/indexInfo",
                FuturesRoute::ChangeInitialLeverage => "/fapi/v1/leverage",
                FuturesRoute::Account => "/fapi/v2/account",
                FuturesRoute::OpenOrders => "/fapi/v1/openOrders",
                FuturesRoute::UserDataStream => "/fapi/v1/listenKey",
                FuturesRoute::Income => "/fapi/v1/income",
            },
            Router::Inverse(route) => match route {
                FuturesRoute::Ping => "/dapi/v1/ping",
                FuturesRoute::Time => "/dapi/v1/time",
                FuturesRoute::ExchangeInfo => "/dapi/v1/exchangeInfo",
                FuturesRoute::Depth => "/dapi/v1/depth",
                FuturesRoute::Trades => "/dapi/v1/trades",
                FuturesRoute::HistoricalTrades => "/dapi/v1/historicalTrades",
                FuturesRoute::AggTrades => "/dapi/v1/aggTrades",
                FuturesRoute::Klines => "/dapi/v1/klines",
                FuturesRoute::ContinuousKlines => "/dapi/v1/continuousKlines",
                FuturesRoute::IndexPriceKlines => "/dapi/v1/indexPriceKlines",
                FuturesRoute::MarkPriceKlines => "/dapi/v1/markPriceKlines",
                FuturesRoute::PremiumIndex => "/dapi/v1/premiumIndex",
                FuturesRoute::FundingRate => "/dapi/v1/fundingRate",
                FuturesRoute::Ticker24hr => "/dapi/v1/ticker/24hr",
                FuturesRoute::TickerPrice => "/dapi/v1/ticker/price",
                FuturesRoute::BookTicker => "/dapi/v1/ticker/bookTicker",
                FuturesRoute::AllForceOrders => "/dapi/v1/allForceOrders",
                FuturesRoute::AllOpenOrders => "/dapi/v1/allOpenOrders",
                FuturesRoute::AllOrders => "/dapi/v1/allOrders",
                FuturesRoute::UserTrades => "/dapi/v1/userTrades",
                FuturesRoute::PositionSide => "/dapi/v1/positionSide/dual",
                FuturesRoute::Order => "/dapi/v1/order",
                FuturesRoute::PositionRisk => "/dapi/v1/positionRisk",
                FuturesRoute::LeverageBracket => "/dapi/v2/leverageBracket",
                FuturesRoute::Balance => "/dapi/v1/balance",
                FuturesRoute::OpenInterest => "/dapi/v1/openInterest",
                FuturesRoute::OpenInterestHist => "/futures/data/openInterestHist",
                FuturesRoute::TopLongShortAccountRatio => "/futures/data/topLongShortAccountRatio",
                FuturesRoute::TopLongShortPositionRatio => "/futures/data/topLongShortPositionRatio",
                FuturesRoute::GlobalLongShortAccountRatio => "/futures/data/globalLongShortAccountRatio",
                FuturesRoute::TakerlongshortRatio => "null",
                FuturesRoute::LvtKlines => "null",
                FuturesRoute::IndexInfo => "null",
                FuturesRoute::ChangeInitialLeverage => "/dapi/v1/leverage",
                FuturesRoute::Account => "/dapi/v1/account",
                FuturesRoute::OpenOrders => "/dapi/v1/openOrders",
                FuturesRoute::UserDataStream => "/dapi/v1/listenKey",
                FuturesRoute::Income => "/dapi/v1/income",
            }
        })
    }
}